### ISSUE TITLE
CRUD pages HTTP-Error-500 on create new or edit

### ISSUE THREAD

**Issue by GMDuncan** [jncc/web-mapper-core#78]
Hi, currently getting an HTTP-Error-500 on https://api.emodnet-seabedhabitats.eu/ when trying to create new in any of the tables, or edit existing records. I can view the pages fine (when bypassing the JNCC proxy), but errors show after clicking the "Create New" or "Edit" links.

I'm not sure if this is an entirely new issue or related to #69

**Comment by SimonAnnetts** [comment]
Hi @GMDuncan 
I can no longer access https://api.emodnet-seabedhabitats.eu/Index1 so I can't see what is happening. Can this be allowed to 82.69.43.209 ?

**Comment by SimonAnnetts** [comment]
sorry, actually I mean access to all pages  - probably only /api/* is now allowed to everyone and everything else is tied to your IP, so if our IP can be added to that apche rule also? Thanks

**Comment by GMDuncan** [comment]
@paul-gilbertson are you able to allow the IP above for @SimonAnnetts to access for testing? Please note, we do have a workaround currently for adding new layers directly into the database rather than through the CRUD pages, so the urgency is not 'catastrophic' here!

**Comment by GMDuncan** [comment]
Appears fixed now (i.e. when I click "Create New" I get brought through to the correct page)

Has this been fixed @SimonAnnetts ? Will close the issue if so!

**Comment by SimonAnnetts** [comment]
I haven't done anything as I still don't have access to see what was broken - but if it's working again now? Possibly was an IP restriction or misconfiguration on the webserver proxy at your end or something? Maybe Paul fixed it.

**Comment by GMDuncan** [comment]
Yes appears to be working now, I'll close this issue currently and double check with paul et al to see if anything was done on our end. Thanks Simon.
